name = "yj-invest"
type = "javascript"
account_id = ""
workers_dev = true

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["app/**/*.ts", "app/**/*.tsx"]

[env.production]
vars = { ENVIRONMENT = "production", NODE_VERSION = "20" }

[observability]
enabled = true
